# Generated by Django 4.1.3 on 2022-11-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción corta'),
        ),
    ]
