# Generated by Django 4.1.3 on 2022-11-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unidades disponibles'),
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='URL Mercadolibre'),
        ),
    ]
